### ISSUE TITLE
Use org.freedesktop.Platform.GL32 version 21.08

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.valvesoftware.Steam#808]
Hey,

I was going through the configuration for 32bit, and one of the things I noticed what that you define both 21.08 and 1.4, but you use 1.4:

```
  org.freedesktop.Platform.GL32:
    directory: lib/i386-linux-gnu/GL
    version: '1.4'
    versions: 21.08;1.4
    subdirectories: true
    no-autodownload: true
    autodelete: false
    add-ld-path: lib
    merge-dirs: vulkan/icd.d;glvnd/egl_vendor.d;OpenCL/vendors;lib/dri;lib/d3d;vulkan/explicit_layer.d
    download-if: active-gl-driver
    enable-if: active-gl-driver
```

Should this not be changed to;
```
  org.freedesktop.Platform.GL32:
    directory: lib/i386-linux-gnu/GL
    version: '21.08'
    versions: 21.08;1.4
    subdirectories: true
    no-autodownload: true
    autodelete: false
    add-ld-path: lib
    merge-dirs: vulkan/icd.d;glvnd/egl_vendor.d;OpenCL/vendors;lib/dri;lib/d3d;vulkan/explicit_layer.d
    download-if: active-gl-driver
    enable-if: active-gl-driver
```

I'm not actually sure how much impact this have, or how to test it, but I did find it odd.
